name: Run Tests and Generate Cucumber Report

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run only API (non-UI) tests
      - name: Run Cucumber tests
        run: mvn clean test -Dcucumber.filter.tags="@api" -e -X
        # If using Maven profiles:
        # run: mvn clean test -Papi-tests

      - name: Show Surefire Test Reports on Failure
        if: failure()
        run: |
          echo "===== TEST REPORTS ====="
          cat target/surefire-reports/*.txt || true

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Upload Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports
